# Generated by Django 4.1.7 on 2023-03-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_announcement_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='like_new',
            field=models.BooleanField(default=False),
        ),
    ]
