# Generated by Django 4.1.7 on 2023-03-21 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_announcement_like_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='like_new',
        ),
    ]
